#!/usr/bin/env python3
import argparse
import struct
import sys
import zipfile

class JavaClassParser:
    def __init__(self, data):
        self.data = data
        self.offset = 0
        self.constant_pool = []

    def read(self, fmt):
        size = struct.calcsize(fmt)
        result = struct.unpack_from(fmt, self.data, self.offset)
        self.offset += size
        return result

    def parse(self):
        magic, = self.read(">I")
        if magic != 0xCAFEBABE:
            print(f"[Error] 不正なマジックナンバー: {hex(magic)}", file=sys.stderr)
            return False

        minor, major = self.read(">HH")
        print(f"[Info] Classバージョン: Major={major}, Minor={minor}")

        cp_count, = self.read(">H")
        self.constant_pool = [None] * cp_count
        
        i = 1
        while i < cp_count:
            tag, = self.read(">B")
            if tag == 1: # CONSTANT_Utf8
                length, = self.read(">H")
                string_data = self.data[self.offset:self.offset+length].decode('utf-8', errors='ignore')
                self.offset += length
                self.constant_pool[i] = {"tag": "Utf8", "value": string_data}
            elif tag in (7, 8): # Class, String
                name_index, = self.read(">H")
                self.constant_pool[i] = {"tag": "Ref", "index": name_index}
            elif tag in (9, 10, 11): # Fieldref, Methodref
                class_index, name_and_type_index = self.read(">HH")
                self.constant_pool[i] = {"tag": "MemberRef", "class": class_index, "nat": name_and_type_index}
            elif tag == 12: # NameAndType
                name_index, descriptor_index = self.read(">HH")
                self.constant_pool[i] = {"tag": "NameAndType", "name": name_index, "desc": descriptor_index}
            elif tag in (3, 4): # Integer, Float
                self.read(">I")
                self.constant_pool[i] = {"tag": "Value"}
            elif tag in (5, 6): # Long, Double
                self.read(">Q")
                self.constant_pool[i] = {"tag": "ValueLong"}
                i += 1
            elif tag in (15, 16, 18, 19, 20):
                self.read(">H")
                self.constant_pool[i] = {"tag": "InvokeDynamic"}
            else:
                self.constant_pool[i] = {"tag": f"Unknown({tag})"}
            i += 1

        print(f"[Info] 定数プールパース完了 (要素数: {len(self.constant_pool)-1})")
        
        self.read(">HHHH")
        interfaces_count, = self.read(">H")
        self.offset += interfaces_count * 2

        fields_count, = self.read(">H")
        for _ in range(fields_count):
            self.read(">HH")
            attributes_count, = self.read(">H")
            for _ in range(attributes_count):
                self.read(">H")
                attr_len, = self.read(">I")
                self.offset += attr_len

        methods_count, = self.read(">H")
        main_bytecode = None
        
        for _ in range(methods_count):
            access_flags, name_index, descriptor_index, attributes_count = self.read(">HHHH")
            method_name = self.constant_pool[name_index]["value"]
            
            for _ in range(attributes_count):
                attr_name_index, = self.read(">H")
                attr_len, = self.read(">I")
                attr_name = self.constant_pool[attr_name_index]["value"]
                
                if attr_name == "Code" and method_name == "main":
                    max_stack, max_locals, code_length = self.read(">HHI")
                    main_bytecode = self.data[self.offset : self.offset + code_length]
                    self.offset += code_length
                    
                    exception_table_length, = self.read(">H")
                    self.offset += exception_table_length * 8
                    code_attr_count, = self.read(">H")
                    for _ in range(code_attr_count):
                        self.read(">H")
                        l, = self.read(">I")
                        self.offset += l
                else:
                    self.offset += attr_len

        if main_bytecode:
            return main_bytecode
        return False

def generate_llvm(parser, bytecode):
    llvm_lines = [
        "; Generated by Custom jar2ll CLI (JDK 25)",
        "declare i32 @jdk_unimplemented_instruction(i32)",
        "declare void @jdk_init_runtime()",
        "declare void @jdk_print_string(i8*)",
        "",
        "define void @Java_Main_main() {",
        "entry:"
    ]

    pc = 0
    reg_id = 1
    simulated_stack = []

    while pc < len(bytecode):
        opcode = bytecode[pc]
        
        if opcode == 0xb2: # getstatic
            field_idx, = struct.unpack_from(">H", bytecode, pc + 1)
            llvm_lines.append(f"  ; [pc {pc}] getstatic")
            llvm_lines.append(f"  %{reg_id} = alloca i8*, align 8")
            simulated_stack.append(f"%{reg_id}")
            reg_id += 1
            pc += 3
        elif opcode == 0x12: # ldc
            cp_idx = bytecode[pc + 1]
            llvm_lines.append(f"  ; [pc {pc}] ldc")
            llvm_lines.append(f"  %{reg_id} = alloca i8*, align 8")
            simulated_stack.append(f"\"_string_cp_{cp_idx}\"")
            reg_id += 1
            pc += 2
        elif opcode == 0xb6: # invokevirtual
            method_idx, = struct.unpack_from(">H", bytecode, pc + 1)
            method_ref = parser.constant_pool[method_idx]
            nat_ref = parser.constant_pool[method_ref["nat"]]
            method_name = parser.constant_pool[nat_ref["name"]]["value"]
            llvm_lines.append(f"  ; [pc {pc}] invokevirtual: {method_name}")
            
            if len(simulated_stack) >= 2:
                simulated_stack.pop()
                simulated_stack.pop()
                if method_name == "println":
                    llvm_lines.append(f"  call void @jdk_print_string(i8* null)")
            pc += 3
        elif opcode == 0xb1: # return
            llvm_lines.append(f"  ; [pc {pc}] return")
            llvm_lines.append("  ret void")
            pc += 1
        else:
            llvm_lines.append(f"  ; [pc {pc}] 未対応命令: {hex(opcode)}")
            llvm_lines.append(f"  %{reg_id} = call i32 @jdk_unimplemented_instruction(i32 {opcode})")
            reg_id += 1
            pc += 1

    llvm_lines.append("}")
    llvm_lines.extend(["", "define i32 @main() {", "  call void @jdk_init_runtime()", "  call void @Java_Main_main()", "  ret i32 0", "}"])
    return "\n".join(llvm_lines)

def main():
    parser = argparse.ArgumentParser(description="Java to LLVM IR CLI Converter")
    parser.add_argument("input_file", help="Path to .class or .jar")
    args = parser.parse_args()

    data = None
    if args.input_file.endswith(".jar"):
        with zipfile.ZipFile(args.input_file, 'r') as jar:
            class_files = [f for f in jar.namelist() if f.endswith(".class")]
            if not class_files:
                sys.exit(1)
            with jar.open(class_files[0]) as f:
                data = f.read()
    else:
        with open(args.input_file, "rb") as f:
            data = f.read()

    jcp = JavaClassParser(data)
    bytecode = jcp.parse()
    if bytecode:
        llvm_text = generate_llvm(jcp, bytecode)
        with open("output.ll", "w") as f:
            f.write(llvm_text)
        print("[Success] output.ll を生成しました！")
    else:
        print("[Error] 変換に失敗しました。")
        sys.exit(1)

if __name__ == "__main__":
    main()
