name: dex2ll

on:
  push:
    paths:
      - "*.apk"
  workflow_dispatch:

jobs:
  decompile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install baksmali
        run: |
          curl -L "https://github.com/kakaomames/so2Ilvm/releases/download/cat/cell.apks" -o cell.apks
          curl -L "https://github.com/kakaomames/so2Ilvm/releases/download/cell/APKEditor.jar" -o APKEditor.jar
          java -jar APKEditor.jar m -i cell.apks -o cell.apk
          rm -rfv cell.apks
          wget https://github.com/JesusFreke/smali/releases/download/v2.5.2/baksmali-2.5.2.jar -O baksmali.jar

      - name: Extract classes.dex from APK
        run: |
          mkdir dex
          unzip *.apk classes*.dex -d dex

      - name: Convert DEX → Smali
        run: |
          mkdir smali
          java -jar baksmali.jar d dex/classes.dex -o smali

      - name: Upload smali output
        uses: actions/upload-artifact@v4
        with:
          name: smali
          path: smali
          
      - name: Run smali2ssa
        run: |
          mkdir -p ssa
          python tools/smali2ssa.py smali/ ssa/

      - name: Upload SSA IR
        uses: actions/upload-artifact@v4
        with:
          name: ssa-ir
          path: ssa
