name:  Jar2Wasm Pipeline v2 !

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            default-jdk \
            python3 \
            llvm \
            clang \
            lld \
            wabt \
            unzip

      - name: Downloading to Minecraft Java Edition jar file by mojang.com
        run: |
          echo "Simple"
          curl -L "https://piston-data.mojang.com/v1/objects/fd19469fed4a4b4c15b2d5133985f0e3e7816a8a/client.jar" -o target.jar

      - name: Downloading bytecoder.jar
        run: |
          curl -sSL "https://repo.maven.apache.org/maven2/de/mirkosertic/bytecoder/bytecoder-cli/2023-05-19/bytecoder-cli-2023-05-19-executable.jar" -o "bytecoder-cli.jar"     
          curl -sSL "https://piston-meta.mojang.com/v1/packages/efcf0cda32d7ebf3ce3938d9add0179cfedeb0c0/1.20.4.json" -o version.json
          jq version.json | head -20 version.json || true
          # output.ll
    
      - name: Download to lib jar file
        run: |
          echo "Parsing JSON and downloading libraries dynamically..."
          jq -r '.libraries[].downloads.artifact | select(. != null) | "\(.url)\t\(.path)"' version.json | while IFS=$'\t' read -r url path; do
            mkdir -p "./libraries/$(dirname "$path")"
            echo "Downloading to ./libraries/$path ..."
            curl -sL "$url" -o "./libraries/$path"
          done


      - name: Build wasm by Bytecoder
        run: |
          echo "Constructing Comma-Separated Classpath for Bytecoder..."
          CLASSPATH_STR=$(find ./libraries -name "*.jar" | paste -sd, -)
          FULL_CLASSPATH="target.jar,$CLASSPATH_STR"
          
          find ./libraries -name "*.jar" | paste -sd, -
          
          mkdir -p ./dist
          cp target.jar dist/target.jar
          unzip -o test.jar -d ./dist
          
          java -jar bytecoder-cli.jar compile wasm \
            -classpath="$FULL_CLASSPATH" \
            -mainclass=net.minecraft.client.main.Main \
            -builddirectory=./dist || echo "Bytecoder finished with some status/errors"


      - name: 404!
        run: |
          # wasm2wat output.wasm -o output.wat
          # cat output.wat
          # https://repo.maven.apache.org/maven2/de/mirkosertic/bytecoder/bytecoder-cli/2023-05-19/bytecoder-cli-2023-05-19-executable.jar

      - name: Upload
        uses: actions/upload-artifact@v4  
        with:
          name: compiled-wasm-client
          path: ./dist/
